parameters:
    cron.resolver.class:        Cron\CronBundle\Cron\Resolver
    cron.manager.class:         Cron\CronBundle\Cron\Manager
    cron.command_builder.class: Cron\CronBundle\Cron\CommandBuilder
    cron.executor.class:        Cron\Executor\Executor
    cron.validator.class:       Cron\Validator\CrontabValidator

services:
    Cron\CronBundle\Command\CronRunCommand:
        arguments: [ "@cron.executor", "@cron.resolver", "@cron.manager"]
        tags: [console.command]
    cron.resolver:
        class: "%cron.resolver.class%"
        arguments: ["@cron.manager", "@cron.command_builder", "%kernel.project_dir%"]
    cron.manager:
        class: "%cron.manager.class%"
        arguments: ["@doctrine"]
    cron.executor:
        class: "%cron.executor.class%"
    cron.command_builder:
        class: "%cron.command_builder.class%"
        arguments: ["%kernel.environment%"]
    cron.validator:
        class: "%cron.validator.class%"
